config:
  base: examples/demo/
  compress: true
  csv:
    columns:
    - x
    - y
    - z
    compress: true
    delimiter: ','
    header: 1
  file: configuration.yaml
  inputPath: input/
  modelFileVtk: model.vts
  outputPath: ''
  shapePath: ''
model:
  3d: true
  cellNumberX: 50
  cellNumberY: 50
  cellNumberZ: 50
  cornerPoint1:
  - 0.0
  - 0.0
  - 0.0
  cornerPoint2:
  - 5.0
  - 0.0
  - 0.0
  dimension:
  - 5.0
  - 10.0
  - 10.0
  discretisationType: n
  discretisationX:
  - 2
  - 1
  - 2
  discretisationY:
  - 2
  - 1
  - 1
  - 5
  - 1
  discretisationZ:
  - 3
  - 3
  - 1
  partitionId:
    all: 0
    crack1: 4
    default: 1
    layer-1: 3
    layer-2: 2
  structureRank:
    crack1: 1
    layer-1: 5
    layer-2: 10
  structureWidth:
    crack1: 1
structure:
  extension:
  file:
  - crack1.csv
  - layer-1.csv
  - layer-2.csv
  - lateralmask.asc
  type:
  - fault
  - layer
  - layer
  - mask
